### ISSUE TITLE
Add description, inputs and outputs for bio_embeddings.visualize.html

### ISSUE THREAD

**Issue by konstin** [sacdallago/bio_embeddings#106]
Note to self @sacdallago 
Add description, inputs and oputputs for https://docs.bioembeddings.com/modules/bio_embeddings.visualize.html

Relevant for protocol!

_Originally posted by @sacdallago in https://github.com/sacdallago/bio_embeddings/issues/93#issuecomment-731076308_

**Comment by sacdallago** [comment]
I feel like this was done https://docs.bioembeddings.com/api/bio_embeddings.visualize.html
