### ISSUE TITLE
BUG: AttributeError: module 'torch.jit' has no attribute '_script_if_tracing'

### ISSUE THREAD

**Issue by KacperStasieluk** [sacdallago/bio_embeddings#111]
Hello everyone,
When trying to execute the code below:

`from bio_embeddings.embed import SeqVecEmbedder`
`embedder = SeqVecEmbedder()`
`embedding = embedder.embed("SEQVENCE")`

I got an error that reads as follows:

> AttributeError: module 'torch.jit' has no attribute '_script_if_tracing'

But the said information was not the cause of the problem. Instead, they were conflicting versions of the torch, torchvision, and pillow libraries that do not interact with the bio_embeddings library.

The bug was resolved by downgrading these libraries to the following versions:

> torch: 1.5.0
> torchvision: 0.6.0
> pillow: 7.0.0

What is easy to do with commands such as: 

`pip install torch==1.5.0 torchvision==0.6.0 pillow==7.0.0`

After reinstalling the libraries in the appropriate versions this time, the code ran without any problems. 

Regardless of everything, I consider it a bug, because by misdiagnosing the cause of the problem, you can waste a lot of time looking for a solution on the wrong pages when the solution is so simple. 

Best regards,
Kacper Stasiełuk

**Comment by konstin** [comment]
Hi Kacper, thanks for reporting this. Do you know which combination of torch, torchvision and pillow versions caused the error? With `pip install -U bio_embeddings` I got 1.5.1, 0.6.1 and 8.1.0, with which the error doesn't occur. You should be able to check with:

```python
import importlib_metadata
print(
    importlib_metadata.version("torch"),
    importlib_metadata.version("torchvision"),
    importlib_metadata.version("pillow"),
)
```

If I know which version causes the problem, I can add a constrained that prevents that version from being installed.

**Comment by KacperStasieluk** [comment]
For some reason, I have now changed the environment to Google Colab, but was able to reproduce the bug successfully.

In this particular case, the following versions are causing the problem:

> torch: 1.5.1
> torchvision: 0.8.1
> pillow: 7.0.0

From which I conclude that the most likely problem is the too high version of **torchvision**. It seems to me that the other libraries are of little importance in this case.

**Comment by konstin** [comment]
I've updated torch to 1.7, so torchvision should now work. Please feel to open another issue if something is still broken
