### ISSUE TITLE
Getting tqdm error on Colab

### ISSUE THREAD

**Issue by sacdallago** [sacdallago/bio_embeddings#123]
Executing: https://colab.research.google.com/github/sacdallago/bio_embeddings/blob/develop/notebooks/extract_supervised_from_seqvec.ipynb

I get:

![image](https://user-images.githubusercontent.com/6240943/112757255-4011ea80-8fe9-11eb-8faf-029f40f49e80.png)

this error goes away after I re-execute the pip3 install commands.

High prio because relevant for protocol users!

**Comment by konstin** [comment]
I've filed an issue upstream: https://github.com/huggingface/transformers/issues/10964. In summary, transformers uses pkg_resources with uses a cache which does only get updated when restarting the runtime or flushing the cache manually. Until we get a response from transformers, if you want I can add a very hacky workaround.

**Comment by sacdallago** [comment]
:D and you received praise from the transformers team, not bad ;) and you'll be a contributor to huggingface, what a prolific coder

No hacks for now, let's see how quickly they merge your PR (I'd assume: quickly)
