### ISSUE TITLE
Remove dependency from ruamel_yaml

### ISSUE THREAD

**Issue by sacdallago** [sacdallago/bio_embeddings#13]
Remove dependency from `ruamel_yaml` and use `pyyaml` instead.

**Comment by konstin** [comment]
@sacdallago I can take this if you want it should be a quick change anyway.

**Comment by sacdallago** [comment]
Sounds good. I've already experimented with https://pyyaml.org/ which seems to do the trick.

Things that I didn't quite figure out from that library:
- Is it possible to preserve comments?
- Will the files be stored in order (in the pipeline, the order of keys matters!)
- Can you store the file without pythonification of the original object type (e.g.: [this line](https://github.com/sacdallago/consurf_extractor/blob/master/out_config.yml#L1) I don't like :D)

**Comment by konstin** [comment]
> Is it possible to preserve comments?

No, pyyaml does only preserve the data, not comments or indentation. If keeping comments is a requirement, we need to stick with ruamel_yaml.

**Comment by sacdallago** [comment]
Hm.

Though one.

I think it's OK to remove comments. After all: we just copy the configs... they will still have the original somewhere.

IDK if `ruamel_yaml ` has become more stable, but when we were releasing `0.1.3` they were migrating to another versioning system and that resulted in weird versioning errors when clean-installing the pipeline.

Opinions?

**Comment by konstin** [comment]
If that's the problem we can just pin a specific version of ruamel_yaml we know to work.

**Comment by sacdallago** [comment]
Not relevant anymore, closing for now
