### ISSUE TITLE
reduce_per_protein for glove, word2vec and fasttext

### ISSUE THREAD

**Issue by tijeco** [sacdallago/bio_embeddings#134]
I noticed ya'll have `reduce_per_protein` set as todo for  glove, word2vec and fasttext. I also noticed that most of the time this function either returns `embedding.mean(axis=0)` or `embedding.sum(0).mean(0)`. For these three embeddings, would it also be something as simple as that?

**Comment by sacdallago** [comment]
hey. Yes, it would. Reason we haven't worked on these is that all other approaches are just soooooo much better. But for sake of completeness, we may finish these up, too
