### ISSUE TITLE
Protocol plotly: RuntimeError: Expected embeddings in projected_reduced_embeddings_file to be of shape (3,), not (2,)

### ISSUE THREAD

**Issue by oberguiuc** [sacdallago/bio_embeddings#141]
## Metadata
|key|value|
|--|--|
|**version**|0.2.0|
|**cuda**|False|

## Parameter
|key|value|
|--|--|
type|visualize
protocol|plotly
annotation_file|disprot_annotations.csv
display_unknown|False
depends_on|umap_projections

## Traceback
```
Traceback (most recent call last):
  File "/home/n-z/noberg/.local/lib/python3.7/site-packages/bio_embeddings/utilities/pipeline.py", line 280, in execute_pipeline_from_config
    stage_output_parameters = stage_runnable(**stage_parameters)
  File "/home/n-z/noberg/.local/lib/python3.7/site-packages/bio_embeddings/visualize/pipeline.py", line 169, in run
    return PROTOCOLS[kwargs["protocol"]](result_kwargs)
  File "/home/n-z/noberg/.local/lib/python3.7/site-packages/bio_embeddings/visualize/pipeline.py", line 39, in plotly
    f"Expected embeddings in projected_reduced_embeddings_file "
RuntimeError: Expected embeddings in projected_reduced_embeddings_file to be of shape (3,), not (2,)
```

**Comment by oberguiuc** [comment]
config.yml:

`

    global:

    sequences_file: sequences.fasta

    prefix: disprot_sampled

    protbert_embeddings:

    type: embed

    protocol: prottrans_bert_bfd

    reduce: true

    discard_per_amino_acid_embeddings: true

    umap_projections:

    type: project

    protocol: umap

    depends_on: protbert_embeddings

    n_components: 2

    plotly_visualization:

    type: visualize

    protocol: plotly

    annotation_file: disprot_annotations.csv

    display_unknown: false

    depends_on: umap_projections

`

**Comment by sacdallago** [comment]
Thanks @nilsoberg2 , I'll look into this with #136 , these seem to be victims of re-engineering efforts

**Comment by konstin** [comment]
v0.2.1 should contain the fix
