### ISSUE TITLE
ESM-1v support as a ESM1vEmbedder

### ISSUE THREAD

**Issue by ptynecki** [sacdallago/bio_embeddings#142]
Hey,

Alex, Joshua, Roshan and other ESM co-authors just released **ESM-1v**.

**Paper:**
https://www.biorxiv.org/content/10.1101/2021.07.09.450648v1.full.pdf
**Code:**
https://github.com/facebookresearch/esm#main-models-you-should-use-

Regards,
Piotr

**Comment by konstin** [comment]
Definitely want to include this, however I wonder how to deal with that actually being five models. Should we just expose them as five different LMs and let the user do the combining? (From skimming the paper I couldn't find how they actually combine the predictions. Do they just predict 5 times and take the mean?)

**Comment by sacdallago** [comment]
> From skimming the paper I couldn't find how they actually combine the predictions. Do they just predict 5 times and take the mean?

@tomsercu can you help clear this doubt? :) would be greatm, so we can include & make availble at large

@konstin :

> however I wonder how to deal with that actually being five models. Should we just expose them as five different LMs and let the user do the combining? 

Since I suppose that loading each model will have some memory footprint, it may be better to separate them into 5 protocols, if it's really the case that all 5 are run and their results get aggregated in some fashion.

The aggregation can happen in a project-type stage (if at the level of the embedding. otherwsie an extract with multiple dependencies). We might need to extend `depends_on` to accept a list of dependencies, rather than a single dependency.

One issue I see here is that this will have 5x the storage footprint of any other model...

**Comment by tomsercu** [comment]
> From skimming the paper I couldn't find how they actually combine the predictions. Do they just predict 5 times and take the mean?

In the associated paper ([Language models enable zero-shot prediction of the effects of mutations on protein function](https://www.biorxiv.org/content/10.1101/2021.07.09.450648v1.full.pdf)) Page 4 Table 1 it is an ensemble in direct comparison to the DeepSequence setup. Page 6, Table 2 presents both ensemble and average over the 5 models.

Btw, let me know if there's any friction point currently in loading ESM models into bio_embeddings? I remember seeing a while ago some model loading `upgrade_state_dict` code had to be replicated in bio_embeddings - is this still the case and could this be refactored to make your life easier?

**Comment by konstin** [comment]
The ESM package is great to use actually, and `load_model_and_alphabet_core` already handles all state dict matters nicely. The only very minor issue with ESM1v is that there's no flag to skip the `Regression weights not found, predicting contacts will not produce correct results.` warning even though this is not relevant for bio_embeddings.

---

Let me phrase my question regarding the ensemble differently: On page 4 formula 1 you compute the log likelihood using a function `p`. Am I correct to assume that `p` is a single LM (predicting likelihoods just like transformers' `BertForMaskedLM`) and that the ensemble takes the mean over the five log odds ratios?

**Comment by konstin** [comment]
`esm1v` is now available on the develop branch as embedder protocol and in the python api as [ESM1vEmbedder](https://docs.bioembeddings.com/develop/api/bio_embeddings.embed.html#bio_embeddings.embed.ESM1vEmbedder) :rocket:

**Comment by tomsercu** [comment]
@konstin circling back on "ensemble takes the mean over the five log odds ratios?"
You are correct. This is analogous with how deepsequence is ensembled as well. In fact this corresponds to a geometric mean of probabilibities; a arithmetic mean could also be considered but we decided to keep things simply in line with prior work here.
