### ISSUE TITLE
Please give me how i could solve this error

### ISSUE THREAD

**Issue by faruk17035** [sacdallago/bio_embeddings#143]
![image](https://user-images.githubusercontent.com/54856692/125727061-b61fb1e1-ee3a-48cd-8e62-e1a623b8c9fe.png)

**Comment by sacdallago** [comment]
Hi @faruk17035 , as the error indicates, you have duplicate sequences in your FASTA file. Either remove the duplicate sequences or enable simple remapping:  https://github.com/sacdallago/bio_embeddings/blob/develop/examples/parameters_blueprint.yml#L13
