### ISSUE TITLE
Protocol word2vec: InvalidParameterError: Invalid protocol selection: word2vec

### ISSUE THREAD

**Issue by faruk17035** [sacdallago/bio_embeddings#144]
The error is:
![image](https://user-images.githubusercontent.com/54856692/125779027-055d4743-fd52-48eb-9e15-e7dc7e56da9c.png)
Here is the config file:
![image](https://user-images.githubusercontent.com/54856692/125779094-ee24d3c0-03fa-4004-a431-dc3d82230d02.png)

**Comment by sacdallago** [comment]
Hi,

there are several issues here. The main ones are two:

1. As stated in the error message atop, you don't have any extras installed. You need all extras to run all embedders. Thus, the only available protocol is unirep (as stated at the end of the error).
2. You seem to be using Windows, which we don't support. There may be the option of using WSL as [described in our manuscript](https://currentprotocols.onlinelibrary.wiley.com/doi/10.1002/cpz1.113), but that's also out of support for us
