### ISSUE TITLE
Which is my output embedding file from these files(converted to numerical form) and how I work with it ? Please help dear Dallago Sir

### ISSUE THREAD

**Issue by faruk17035** [sacdallago/bio_embeddings#149]
![image](https://user-images.githubusercontent.com/54856692/126433973-b0669c85-b857-4952-bec1-354280e269d2.png)

**Comment by konstin** [comment]
The `embeddings_file.h5` contains the per-residue embeddings, the `reduced_embeddings_file.h5` contains the per-protein embeddings. You can check [this notebook](https://github.com/sacdallago/bio_embeddings/blob/develop/notebooks/open_embedding_file.ipynb) ([colab version](https://colab.research.google.com/github/sacdallago/bio_embeddings/blob/develop/notebooks/open_embedding_file.ipynb)) and [this notebook](https://github.com/sacdallago/bio_embeddings/blob/develop/notebooks/reindex_h5_file.ipynb) ([colab version](https://colab.research.google.com/github/sacdallago/bio_embeddings/blob/develop/notebooks/reindex_h5_file.ipynb)) on how to work with these files. For more general information on working with hdf5 files from python, check the [h5py documentation](https://docs.h5py.org/en/stable/).

**Comment by faruk17035** [comment]
Sir I want to apply CNN or RNN with these numerical file.  But I want a csv
file. Is there any way to get csv file from these h5 file. If not,
please let me know how I apply CNN or RNN on the h5 file.

**Comment by sacdallago** [comment]
Hi @faruk17035 , there is a notebook on how to train a classifier on embeddings here: https://github.com/sacdallago/bio_embeddings/blob/develop/notebooks/deeploc_machine_learning.ipynb

You can use the notebooks @konstin suggested to convert h5s to CSVs
