### ISSUE TITLE
How to solve this error, I put a DNA sequence here in fasta format...But it gives me error(When convet to numerical form using wor2vec). Please give me some guideline.

### ISSUE THREAD

**Issue by faruk17035** [sacdallago/bio_embeddings#151]
![image](https://user-images.githubusercontent.com/54856692/126599032-ab13de94-6044-494a-92ce-669ecdf18f2b.png)

>3VH0A Cell.membrane-M
MHLRHLFSSRLRGSLLLGSLLVVSSFSTQAAEEMLRKAVGKGAYEMAYSQQENALWLATSQSRKLDKGGVVYRLDPVTLEVTQAIHNDLKPFGATINNTTQTLWFGNTVNSAVTAIDAKTGEVKGRLVLDDRKRTEEVRPLQPRELVADDATNTVYISGIGKESVIWVVDGGNIKLKTAIQNTGKMSTGLALDSEGKRLYTTNADGELITIDTADNKILSRKKLLDDGKEHFFINISLDTARQRAFITDSKAAEVLVVDTRNGNILAKVAAPESLAVLFNPARNEAYVTHRQAGKVSVIDAKSYKVVKTFDTPTHPNSLALSADGKTLYVSVKQKSTKQQEATQPDDVIRIAL

![image](https://user-images.githubusercontent.com/54856692/126599298-f05368a8-c64e-4aee-8d0e-0d18f191e602.png)

**Comment by sacdallago** [comment]
Duplicate #150 .

Your issue here though is not dependent on that as what you are showing is an AA sequence and the error message is about a permission issue (probably the file not being in the right directory or alike).

Also, you are using Windows which is not supported.

**Comment by faruk17035** [comment]
Dear Dallago Sir, I use wsl(ubuntu) in windows...but I don't understand why
it give me that error
