### ISSUE TITLE
Warning "Failed to create stage directory" when using overwrite

### ISSUE THREAD

**Issue by konstin** [sacdallago/bio_embeddings#16]
When running a pipeline the second time I get a warning, even though I'm using `--overwrite`:

```
WARNING: Failed to create stage directory my_develop/stage_1.
```

Depending on the desired behaviour, this can e.g. be solved by replacing `os.mkdir(path)` with `os.makedirs(path, exist_ok=True)` or by calling `shutil.rmtree` before if the directory exists.

**Comment by sacdallago** [comment]
I'd rather go for:

```python
        try:
            os.mkdir(path)
        except FileExistsError:
            logger.info("Stage directory %s already exists." % path)
        except OSError:
            logger.warning("Failed to create stage directory %s." % path)
        else:
            logger.info("Successfully created the stage directory %s." % path)
```

I also realized, that we shouldn't just catch the exceptions, but also raise them again (no point in continuing execution if something can't be written). I'll open a PR on gitlab

**Comment by sacdallago** [comment]
P.S.: `shutil.rmtree` would be a bit too destructive for me. I've tried to implement a cheap overwrite, file-by-file, by simply doing:

```python
with open(path, 'w'):
    os.utime(path, None)
```

This will zero the file's contents and update the "last modified" flag 🤷
