### ISSUE TITLE
After converting protein sequences into numbers, Can we apply LSTM model on the generated numerical datset?

### ISSUE THREAD

**Issue by faruk17035** [sacdallago/bio_embeddings#170]
Dear Cristian Dallago Sir,
I wanted to apply LSTM on a numerical dataset for binary classification problems. First of all, I apply the word embedding method to convert text into the numerical dataset.

Can you help me Sir, if possible?

The dataset is look like the following link: (applying glove)
https://drive.google.com/file/d/1yXBXL1GghfGRz5nQeh0V39XqEASwhyEJ/view?usp=sharing

**Comment by sacdallago** [comment]
Hi @faruk17035 ,

sorry for the long wait -- was on a longer leave, and slowly getting back to things. You can apply any method (including, for instance, scikit-learn models) on either residue or sequence embeddigns for binary classification tasks: https://scikit-learn.org/stable/modules/neural_networks_supervised.html

The features will be the embeddings for either residues or sequences
