### ISSUE TITLE
Getting residue scores (original MLM head predictions)

### ISSUE THREAD

**Issue by prihoda** [sacdallago/bio_embeddings#173]
Hi @sacdallago and @konstin. I know how to get embeddings, and how to get downstream predictions from the embeddings (such as secondary structure) using the classification head checkpoints. But is there also a way to get the predictions of the classification head used during the MLM pre-training? 

These would be useful to inform which mutations can be made at each position (e.g. for protein design), and what's the overall likelihood of the input sequence (e.g. for evo-velocity-type tasks).

**Comment by konstin** [comment]
Hi, we actually have a module called "mutagenesis" with an [example](https://github.com/sacdallago/bio_embeddings/tree/develop/examples#mutagenesis) exactly for that, which should hopefully give you those mutation probabilities

**Comment by prihoda** [comment]
Ah, I see, thanks @konstin! So if I understand it correctly, the MLM weights are included, the trick is loading the model using `BertForMaskedLM.from_pretrained` instead of `BertModel.from_pretrained`.
