### ISSUE TITLE
TypeError: load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by nhowla** [sacdallago/bio_embeddings#175]
<img width="1362" alt="Screen Shot 2022-01-09 at 3 22 17 PM" src="https://user-images.githubusercontent.com/91193685/148701502-9254b7f8-ba66-4bf0-924d-e8071e70db62.png">

**Comment by hoangthienan95** [comment]
this is a problem with pyyaml, see https://stackoverflow.com/questions/69564817/typeerror-load-missing-1-required-positional-argument-loader-in-google-col

Just add `!pip install pyyaml==5.4.1` in a cell as the last package installation line, before importing any package

**Comment by sacdallago** [comment]
Thanks for pointing this out. I have collected some dependency issues by now, I'll try to make a new version with current versioning available within the next 2 weeks or so!
