### ISSUE TITLE
How to reset a corrupted model download?

### ISSUE THREAD

**Issue by ms337** [sacdallago/bio_embeddings#182]
Tried to use the ESM1-b embedder. When init for the first time, ran out of space on disk. So the download was incomplete. 
Now when I try to run the script again, the module tries to use the corrupted downloaded file: 

`Python Error: RuntimeError: unexpected EOF, expected 3194894 more bytes. The file might be corrupted.`

Is there a `force_download=True` argument? Or is there anyway to delete the downloaded model manually and reinit? 

Thanks!

**Comment by konstin** [comment]
You can delete the esm1b folder in `~/.cache/bio_embeddings`, then it should do the download again

**Comment by ms337** [comment]
Dont have a `.cache` directory in my home directory

**Comment by johnnytam100** [comment]
same issue, any workaround?
