### ISSUE TITLE
Solubility / Aggregability / Stability

### ISSUE THREAD

**Issue by avilella** [sacdallago/bio_embeddings#193]
Hi,

I found the list of different bio embeddings in this repo today and I was wondering which of the embeddings have code to predict the "Solubility / Aggregability / Stability" or the proteins in 3D structure. E.g. PLUS mentions Solubility, but there is only a "train" or "eval" python script. I presume this means there is no straight way to "predict" based on the PLUS repo?

**Comment by sacdallago** [comment]
Hi @avilella , thanks for pining.

bio-embeddings was mostly born out of the need to aggregate embeddings from different models around a unified interface. We later added some prediction models (in the extract stage) on top of some of the embeddings, specifically the ones that we published in the lab. One of those models (light attention) predicts solubility, based on the DeepLoc v1 dataset (https://academic.oup.com/bioinformaticsadvances/article/1/1/vbab035/6432029). Sadly, we do not feature the prediction models from PLUS. You can however use the emebddings outputted from the pipeline as input features to train a model of your choice, with whatever framework you prefer!

As a sneak peak: internelly we are woring on a new solution to train using embeddings on selected datasets, and then use these to make inference, but it's at least a month away from public release.

**Comment by avilella** [comment]
Thanks, I presume I can run the "light attention" solubility prediction from the `cli.py`? Does it give a quantitative measure other than categorical answer?

**Comment by sacdallago** [comment]
Yop, here's an example: https://github.com/sacdallago/bio_embeddings/tree/develop/examples/light_attention

**Comment by avilella** [comment]
Could we have the website display the quantitative prediction for solubility next to the categorical one? Thx in advance.

I haven't managed yet to make it work locally (issues with the Nvidia GPU drivers) but it'd be good to try a few on the webpage.

**Comment by sacdallago** [comment]
Hi, no, unfortunately for now we don't plan to add this feature to the webserver. We'll consider it for future iterations.
