### ISSUE TITLE
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

### ISSUE THREAD

**Issue by avilella** [sacdallago/bio_embeddings#194]
I've downloaded the latest docker image on an Ubuntu Linux 21.10 computer which contains a 16GB NVidia GPU (and 6 more NVidia GPUs with 4GB of RAM).

```
$ docker run --rm --gpus all \
    -v "$(pwd)/examples/docker":/mnt \
    -v bio_embeddings_weights_cache:/root/.cache/bio_embeddings \
    -u $(id -u ${USER}):$(id -g ${USER}) \
    ghcr.io/bioembeddings/bio_embeddings:latest /mnt/config.yml
Unable to find image 'ghcr.io/bioembeddings/bio_embeddings:latest' locally
latest: Pulling from bioembeddings/bio_embeddings
da7391352a9b: Pull complete 
14428a6d4bcd: Pull complete 
2c2d948710f2: Pull complete 
0ebd322634c1: Pull complete 
36520dd466ac: Pull complete 
fe6ccac2e64b: Pull complete 
d98e4e0e26f4: Pull complete 
de78c6327017: Pull complete 
dacbe9dde10f: Pull complete 
e421ad06bd0c: Pull complete 
4a0309267055: Pull complete 
Digest: sha256:9e2365604528f80f38a66083d98a3c8af49cca1e973cbd93f476231ae1d23a8b
Status: Downloaded newer image for ghcr.io/bioembeddings/bio_embeddings:latest
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
(base) petmedix@LS4:~$ docker run --rm --gpus 6     -v "$(pwd)/examples/docker":/mnt     -v bio_embeddings_weights_cache:/root/.cache/bio_embeddings     -u $(id -u ${USER}):$(id -g ${USER})     ghcr.io/bioembeddings/bio_embeddings:latest /mnt/config.yml
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
```

How do I point the GPUs to the docker container? Thanks

**Comment by sacdallago** [comment]
Hmm, sorry, this looks like a driver/docker issue which is new to me & I wouldn't know how to help you out. Have you tried to see if the simple smi docker nvidia works? `docker run --rm --gpus all nvidia/cuda nvidia-smi`, or `docker run --rm --gpus 6 nvidia/cuda nvidia-smi`

**Comment by avilella** [comment]
Oh, I see. I think this is an Unsupported distribution by nvidia docker.

**Comment by avilella** [comment]
I managed to replicate the steps of Dockerfile in the machine itself. It
wasn't clear to me that the command-line was going to be the one below
after the poetry-based installation:

~/bio_embeddings$ ~/.local/bin/bio_embeddings
~/bio_embeddings/examples/light_attention/config.yml
2022-05-09 13:58:29,683 INFO Created the prefix directory la_prott5
2022-05-09 13:58:29,683 INFO Created the file
la_prott5/input_parameters_file.yml
2022-05-09 13:58:29,720 INFO Created the file la_prott5/sequences_file.fasta
2022-05-09 13:58:29,722 INFO Created the file la_prott5/mapping_file.csv
2022-05-09 13:58:29,723 INFO Created the file
la_prott5/remapped_sequences_file.fasta
2022-05-09 13:58:29,726 INFO Created the stage directory
la_prott5/t5_embeddings
2022-05-09 13:58:29,726 INFO Created the file
la_prott5/t5_embeddings/input_parameters_file.yml
2022-05-09 13:58:29,729 INFO Downloading model_folder_zip for
prottrans_t5_xl_u50 and storing in '/tmp/tmptawp589m'.

**Comment by sacdallago** [comment]
great to hear you found a solution
