### ISSUE TITLE
How to solve this error?

### ISSUE THREAD

**Issue by faruk17035** [sacdallago/bio_embeddings#196]
![image](https://user-images.githubusercontent.com/54856692/168855412-bb6a59c4-7bac-4608-9ad3-01ad052e712e.png)

**Comment by faruk17035** [comment]
I think there is no identical sequences in my dataset

**Comment by sacdallago** [comment]
You can find some discussion about that here: https://github.com/sacdallago/bio_embeddings/issues/42#issuecomment-670849033
