### ISSUE TITLE
Text on embed.predictprotein.org

### ISSUE THREAD

**Issue by C-Marquet** [sacdallago/bio_embeddings#202]
1. Header: Lamdba -> Lambda
2. Navigate to desired features: toplogy -> topology
3. print friendly page: toplogy -> topology
4. sometimes subcellular location and sometimes localization (not sure if thats relevant)
5. VESPAi -> VESPAl (L for light)
6. Glossary: still says EMPP

**Comment by sacdallago** [comment]
Moving issue
