### ISSUE TITLE
Integrate provis

### ISSUE THREAD

**Issue by sacdallago** [sacdallago/bio_embeddings#21]
https://github.com/salesforce/provis

**Comment by konstin** [comment]
Proper python packages with python 3.6 support, but not published on pypi. Also all requirements are pinned to exact versions, which will clash with our other requirements (esp. their `torch==1.4.0`)

**Comment by sacdallago** [comment]
That's nice and bad at the same time :D

**Comment by konstin** [comment]
provis is actually just an evaluation of tape's bert model (it even uses tape's download mechanism). So if we'd do this it would rather be integrating tape.

**Comment by sacdallago** [comment]
RE Tape, the thing that would be interesting is the evaluation pipeline. I have a hunch that this is going to be picked by less experienced peer reviewers as a "should be in there".
