### ISSUE TITLE
Integrate PLUS

### ISSUE THREAD

**Issue by sacdallago** [sacdallago/bio_embeddings#22]
https://github.com/mswzeus/PLUS/

**Comment by konstin** [comment]
Also requires 3.7, even though all dependencies should work on 3.6. There isn't a python package, so if we don't want to vendor their code, we need to create a python package.

**Comment by sacdallago** [comment]
TBH, although ugly, for some of these things I'm happy even sys-calling them. After all: we are doing them a favor by integrating their tools, "worst comes to worst" they can collaborate with us! Easiest solution! Sys-calls (to e.g. docker containers) could be an interesting extension of the pipeline
