### ISSUE TITLE
Please upload the Albert weight file

### ISSUE THREAD

**Issue by sbasak3** [sacdallago/bio_embeddings#23]

**Comment by sacdallago** [comment]
Hi @sbasak3 , the Albert weight files are not currently freely available as we are pending publication on that model. We expect a preprint of that work to be online shortly (1 week from now; @agemagician and @mheinzinger correct me if I'm wrong). Once that's the case, the weights will be made available online. If you need the weights before that (within the next 7 days), please contact us at `dl <at> rostlab <dot> org`.

Thanks!

**Comment by sacdallago** [comment]
They are available for download now: http://maintenance.dallago.us/public/embeddings/embedding_models/
