### ISSUE TITLE
Decouple LM dependencies from package dependencies

### ISSUE THREAD

**Issue by sacdallago** [sacdallago/bio_embeddings#29]
@konstin proposed some new fancy thing that allows to have different levels of dependencies (like modules in `npm`) in the same pip installable package. This will be particularily useful once we have more LMs (and even now, with the gigantic allennlp depenency + transformers dependency).

**Comment by konstin** [comment]
Both seqvec/allennlp and transformers now have their own extra.

**Comment by sacdallago** [comment]
Reminder: extra for seqvec & for bert should also install pytroch because in extract these are needed to extract supervised features. (probably useful to document somewhere)

**Comment by konstin** [comment]
Both do since both seqvec and transformers are implemented in pytorch.
