### ISSUE TITLE
CPU fallback for Bert

### ISSUE THREAD

**Issue by sacdallago** [sacdallago/bio_embeddings#35]
As mentioned [here](https://github.com/sacdallago/bio_embeddings/issues/33#issuecomment-659551972), there seems to be a problem with batching in Bert.

The set I've used for the tests is `viruses_90` from the test sets on oculus (in case you want to reproduce the run :) ).

I think that enhancing with the SeqVec `single sequence --> CPU --> fail` strategy will solve this issue, too.

**Comment by konstin** [comment]
As memory consumption grows quadratically per sequence, I think we should also try batching by the length squared instead of just the lenght
