### ISSUE TITLE
Inhertiance over helper functions

### ISSUE THREAD

**Issue by sacdallago** [sacdallago/bio_embeddings#36]
Instead of [this](https://github.com/sacdallago/bio_embeddings/blob/develop/bio_embeddings/embed/helper.py#L11), I would rather you create another interface (`TransformerEmbedderInterface`) which extends [`EmbedderInterface`](https://github.com/sacdallago/bio_embeddings/blob/develop/bio_embeddings/embed/embedder_interface.py#L17) and then defines [`embeds_batch`](https://github.com/sacdallago/bio_embeddings/blob/develop/bio_embeddings/embed/bert_embedder.py#L88) at the level of the abstract class.

The rationale: I expect `TransformerEmbedderInterface` to have a class of shared methods which differentiate it slightly from other Embedders, but which need "unity". Specifically, the extraction of the attention activations from the embeddings (something you can't retroactively do).

**Comment by konstin** [comment]
Yeaj, that's why I added the `# TODO: Move this once everything works` at the top of file. I have to check this, but I think we can just use the same class for Bert and Albert, or at least have a common superclass for all embedders.

**Comment by sacdallago** [comment]
Awesome :)

Sorry that I'm opening so many issues, but I'm trying to list things as I ~lose sleep over them~ come across stuff :)
