### ISSUE TITLE
MD5 Clashes among unique sequences

### ISSUE THREAD

**Issue by gregmcinnes** [sacdallago/bio_embeddings#42]
I'm hitting the MD5Clash when I have only unique sequences in my dataset.  I edited the code to remove the exception but there should be an option to ignore this.

    This most likely indicates there are multiple identical sequences in your FASTA file. 
    MD5 hashes are used to remap sequence identifiers from the input FASTA.
    This error exists to prevent wasting resources (computing the same embedding twice).
    There's a (very) low probability of this indicating a real MD5 clash.
    
    If you are sure there are no identical sequences in your set, please open an issue at https://github.com/sacdallago/bio_embeddings/issues . Otherwise, use cd-hit to reduce your input FASTA to exclude identical sequences!
```

**Comment by sacdallago** [comment]
Hey @gregmcinnes 

Thanks for using the `bio_embeddings` pipeline.

I have not had an MD5 hash ever in a sequence diverse (<100% redundancy) set (and this while embedding very large datasets). So, just for the sake of it (although you seem to have done it already): make sure you do not have 100% identical sequences in your set!

Careful! Just commenting out the error will result in unexpected behaviour! When embedding and creating the .h5 files, you will get weird results (you might overwrite the embeddings of two different sequences with the same md5 hash).

We already provide a fallback option: https://github.com/sacdallago/bio_embeddings/blob/develop/examples/parameters_blueprint.yml#L13

Simply set `simple_remapping: True` in the config, this will index your sequences with integers (e.g. `0, 1, 2...`) and is a **much** safer option than commenting out the code yourself!



Let me know if this works for you!
And thank you again for using the pipeline :)

**Comment by gregmcinnes** [comment]
Ok, thanks!  I did check and there are no duplicate sequences.  I didn't see the bit about simple_remapping, that seems useful.

**Comment by konstin** [comment]
The error seems suspicious to me, as the the change of getting a MD5 collision by change is 1.47*10<sup>-29</sup> [[1]](https://www.avira.com/en/blog/md5-the-broken-algorithm), so I rather suspect it's something about the way we process sequences. Could you try inserting the following snippet right before the exception and see what it says?

```python
        import numpy
        for pos in numpy.where(mapping.index.duplicated(False))[0]:
            print(f"The sequence at {pos} clashes: {sequences[pos].seq}")
```
