### ISSUE TITLE
Colab uses CPU instead of GPU although GPU is enabled

### ISSUE THREAD

**Issue by sacdallago** [sacdallago/bio_embeddings#49]
This colab: https://colab.research.google.com/drive/1msZVwcCT2b768HnbRK3SrnmRqtVjvsgg?usp=sharing

Has been set up to use GPU acceleration, however when embedding, it does so on CPU (there's a warning that shows up in the bottom saying "you are connected to a GPU runtime but aren't using the GPU...", and the speed at which it embeds.. well.. Not ideal!). This is weird. Could it be #26 ? @konstin ?

**Comment by konstin** [comment]
This is something about colab, pytorch and/or cuda, but not related to #26. In some other cases the problem was the cuda version, but 10.1 should do fine with pytorch 1.5.1

![grafik](https://user-images.githubusercontent.com/6826232/90959811-92ac8680-e49d-11ea-840a-17b3c3afdbae.png)

**Comment by sacdallago** [comment]
Oh wow, cool way of debugging this! Thanks!!!

Leaving it open for now

**Comment by konstin** [comment]
Note to self: Check against https://github.com/agemagician/ProtTrans/blob/master/Embedding/PyTorch/Basic/ProtBert-BFD.ipynb

**Comment by konstin** [comment]
For reason colab chooses not to disclose to me, it works now

![grafik](https://user-images.githubusercontent.com/6826232/94021281-22529700-fdb4-11ea-8735-c07ca7fb806b.png)

I'd say this is mostly likely either a different torch version or this was fixed in goole colab.

**Comment by sacdallago** [comment]
Fun times...

![image](https://user-images.githubusercontent.com/6240943/97111137-5be12f80-16dd-11eb-9002-d11513c9a501.png)

**Comment by sacdallago** [comment]
But, forcing cuda explains why:

![image](https://user-images.githubusercontent.com/6240943/97111181-ac588d00-16dd-11eb-8347-552b08e45625.png)

We might need to keep torch a few versions behind to run on colab. How is this going to affect other dependencies :thinking:

**Comment by sacdallago** [comment]
Unsuccessfully tried the other way around:

```
!apt-get --purge -y --allow-change-held-packages remove "*cublas*" "cuda*" "nsight*" 
!wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin
!mv cuda-ubuntu1804.pin /etc/apt/preferences.d/cuda-repository-pin-600
!wget https://developer.download.nvidia.com/compute/cuda/11.1.0/local_installers/cuda-repo-ubuntu1804-11-1-local_11.1.0-455.23.05-1_amd64.deb
!dpkg -i cuda-repo-ubuntu1804-11-1-local_11.1.0-455.23.05-1_amd64.deb
!apt-key add /var/cuda-repo-ubuntu1804-11-1-local/7fa2af80.pub
!apt-get update
!apt-get -y install cuda
```

so no point in waisting time there...

**Comment by sacdallago** [comment]
Closing for now, Colab seems to work as intended (which will change suddenly the next time someone at Google sneezes)
