### ISSUE TITLE
Check alphabets

### ISSUE THREAD

**Issue by konstin** [sacdallago/bio_embeddings#54]
Different embedder may be trained on different alphabets, which may be different from those provided by the user.

 * SeqVec has a 25 letter alphabet ("20 standard and 2 rare amino acids (U and O) plus 3 special cases describing either ambiguous (B, Z) or unknown amino acids (X)")
 * The transformers remove the rare amino acids (`re.sub(r"[UZOB]", "X", sequence)`)
 * UniRep has a 26 letter alphabet (https://github.com/ElArkk/jax-unirep/blob/81843c034941cfeb4e45c1808364b5f996771382/tests/test_layers.py#L78)
 * PLUS has 21 letters ("20 proteinogenic and 1 unspecified amino acids")
 * ~~I haven't checked provis~~ provis uses tape while defaulting to `iupac`. Tape has the following code, i.e. they are likely good inspiration for what we want to do:
```python
class TAPETokenizer():
    r"""TAPE Tokenizer. Can use different vocabs depending on the model.
    """

    def __init__(self, vocab: str = 'iupac'):
        if vocab == 'iupac':
            self.vocab = IUPAC_VOCAB
        elif vocab == 'unirep':
            self.vocab = UNIREP_VOCAB
        self.tokens = list(self.vocab.keys())
        self._vocab_type = vocab
        assert self.start_token in self.vocab and self.stop_token in self.vocab
```

We should ensure that whatever alphabet the input fasta uses all embedders work, likely by doing something similar to the transformer, and test that behaviour.

EDIT: Current state on the none-standard amino acids:

* SeqVec: X, O, U, Z, B
* transformer: X, O, U, Z, B (O, U, Z, B -> X internally)
* esm: X, O, U, Z, B
* unirep: X, O, U, Z, B, **J**
* CPCProt (tape): X, O, U, Z, B
* PLUS: X, O, U, Z, B

**Comment by sacdallago** [comment]
Yup, very fair point and another reason why I decided to go for `Bio` instead of using an in-house parser (should make this easier). Nevertheless, as this would be support for external tools, I would suggest to prio:low it.
