### ISSUE TITLE
Installing Develop on windows.

### ISSUE THREAD

**Issue by HannesStark** [sacdallago/bio_embeddings#61]
When trying to install the Develop status like so:
`pip install -U "bio-embeddings[all] @ git+https://github.com/sacdallago/bio_embeddings.git"`
I get an error from jax-unirep that there is no version that satisfies the requirement jaxlib.

Unfortunately, I think jaxlib is not supported for windows right now [#438](https://github.com/google/jax/issues/438)

I can install `pip install bio_embeddings`. Is it possible to install Develop without jaxlib?

**Comment by sacdallago** [comment]
Thanks for documenting the issue @HannesStark :)

For now, there won't be a windows-specific packaging plan, as we focus on cluster execution and linux, and unfortunately no one in the dev team runs a windows machine. Nevertheless, as things stand, there are two solutions for this problem already:

- A fast workaround would be to use docker, but last time we checked (@konstin ) docker-windows didn't support GPU processing
- A somewhat more space intensive workaround would be to use [WSL](https://docs.microsoft.com/en-us/windows/wsl/about), which would give you much better "emulation"


And then there's the naive answer, which could get me banned from GitHub: why windows? :D

**Comment by konstin** [comment]
Self-assigning because I want to document platform support
