### ISSUE TITLE
UniRep takes too much RAM

### ISSUE THREAD

**Issue by konstin** [sacdallago/bio_embeddings#64]
The UniRep embedder continuously uses more RAM, which it shouldn't. I haven't checked yet whether this also happens on the GPU or only on the CPU.

**Comment by sacdallago** [comment]
I remember @mheinzinger complaining about the same thing a year ago. I think he just skipped long sequences.

**Comment by mheinzinger** [comment]
Yes, that's correct: I struggled with exactly the same problem, even though proteins in my set were relatively short. To be honest: I would not spend time on this model as it's impractical to use.
