### ISSUE TITLE
Drop Python 3.6 support

### ISSUE THREAD

**Issue by konstin** [sacdallago/bio_embeddings#66]
According to [numpy's policy](https://numpy.org/neps/nep-0029-deprecation_policy.html), they'll soon remove support for python 3.6, and pandas has already [dropped 3.6](https://github.com/pandas-dev/pandas/pull/35214). This means that in some time we'll have to decide to either drop 3.6 and lose google colab or start lagging behind with the scientific stack.

**Comment by sacdallago** [comment]
I think google will update their runtime before this becomes too much of an issue.

tensorflow relies heavily on numpy for data representation

**Comment by konstin** [comment]
> 🐍🎉  Colab has updated to Python 3.7! 🎉🐍
>
>We've (finally) updated the default python version in Colab for all users. Try it out today!

https://twitter.com/GoogleColab/status/1365062244225060865

**Comment by sacdallago** [comment]
Done, right @konstin ?

**Comment by konstin** [comment]
yes
