### ISSUE TITLE
The AMQP result backend is scheduled for deprecation

### ISSUE THREAD

**Issue by konstin** [sacdallago/bio_embeddings#67]
The worker complains with the following message:

> /app/.venv/lib/python3.6/site-packages/celery/backends/amqp.py:67: CPendingDeprecationWarning: 
> The AMQP result backend is scheduled for deprecation in     version 4.0 and removal in version v5.0.     Please use RPC backend or a persistent 
> alternative='Please use RPC backend or a persistent backend.')

Guess we have to switch at some point.

**Comment by konstin** [comment]
Celery 5 has actually been release a week ago, so this becomes more important

**Comment by sacdallago** [comment]
yeah, I realized this yesterday, too. Was migrating the current celery worker from oculus to LSF and versioning is not fun... I got alennnlp to work, now celery is complaining about not knowing AMQP (note: on their official guide AMQP was suggested as **THE BEST BACKEND**).

![image](https://user-images.githubusercontent.com/6240943/94820529-daa9bc00-0400-11eb-87a6-42cda39fb0f8.png)


UGH.

We can move to redis?

**Comment by konstin** [comment]
I have only have experience with redis and always liked it's simplicity, so I'd be happy about that. However in fairness, this problem is about protocol, not about the broker. It's possible to continue using RabbitMQ by changing the protocol to RPC (see e.g. https://stackoverflow.com/a/48921731/3549270)

**Comment by sacdallago** [comment]
Oh, this was indeed confusing to me -- just protocol, not actual DB.

Well, TBH I don't wanna fiddle around too much with _things that are working_, so I'll try to figure out if moving RabbitMQ to RPC is easy, then I'll simply do that.
