### ISSUE TITLE
nginx caches celery status for too long

### ISSUE THREAD

**Issue by sacdallago** [sacdallago/bio_embeddings#69]
By default, any job is pending (whether it exists or not). First sub-optimal thing in life...

Secondly, it appears that when a job fails (e.g. throws an exception), the job remains "pending". This should not be the case! It should properly fail.

Initial "fixes" don't seem to solve the issue:

![image](https://user-images.githubusercontent.com/6240943/95606809-2f7db000-0a5b-11eb-947e-a60fb13de29e.png)
![image](https://user-images.githubusercontent.com/6240943/95606853-3e646280-0a5b-11eb-8ef5-b124641c6da7.png)

Tried setting the following in the celery worker

```
CELERY_IGNORE_RESULT=False
CELERY_TRACK_STARTED=True
```

based on: https://stackoverflow.com/questions/24148765/celery-task-state-always-pending

**Comment by konstin** [comment]
Could it be that this happens because the error occured in the webserver, not in the worker? Because I think I remember that jobs that failed in the worker show up as failed properly.

**Comment by sacdallago** [comment]
Doubt. That error is logged by the worker. You are correct in that if the webserver fails, the job status won't be affected, but if the webserver fails, the job would have not been tasked to the worker in the first place.

... unless there is some handshaking stuff going on, but given the nature of all of this happening over RabbitMQ, I don't think that's quite it. I think once the webserver tasked the AsyncJob, it just moves on with its life 😎

**Comment by sacdallago** [comment]
I'm not entirely sure, but now it works:

![image](https://user-images.githubusercontent.com/6240943/95725563-1ef65100-0c78-11eb-83a0-74082b6c7baf.png)

I have a hunch.

Since nginx caches responses in the setup of the webserver, if you hit "check status", the "pending" response will be cached for 10m. I now set the cache to cache 2m & delete inactive cache files after 15min, this could be considered a usual "user session".

Leaving this open in case this comes up again in the near future, and I get too annoyed, and just decide to get rid of the cache entirely.

**Comment by konstin** [comment]
Is there a special reason why we have proxy caching in nginx? The whole thing is super fast even without it:

![grafik](https://user-images.githubusercontent.com/6826232/95728831-48b17700-0c7c-11eb-8fb9-bef5df75214f.png)

**Comment by sacdallago** [comment]
yeah, you are looking at simple things :D, once you have to download embedding files, or even prediction files, which are > 240B, you'll see why caching makes sense :)
