### ISSUE TITLE
Keep models in RAM and move to the GPU on demand

### ISSUE THREAD

**Issue by konstin** [sacdallago/bio_embeddings#71]
For the webserver only. This collides with the current way that models are instantiated with their final device.

**Comment by sacdallago** [comment]
I think we don't necessarily have to work around this too much.

I would simply:
 - Have two pytorch device instances, one for CPU one for GPU
 - instantiate the models using the CPU device: https://github.com/sacdallago/bio_embeddings/blob/develop/bio_embeddings/embed/embedder_interfaces.py#L34
 - if embeddings requests are spawned: change the `obj._device` to the GPU, move the `obj._model` to the new device (`.to(obj._device)`), call `.embed(sequence)`, move the _model back to the CPU device.

Two things here:
1. Will moving the device out of GPU memory actually free the memory? #40 
2. How "slow" is this process? 1-2 seconds: ok. > 4 seconds it's questionable

**Comment by sacdallago** [comment]
I think we can archive this as I've simply loaded some models on CPU instead of GPU since we have CPU to spare and web users are anyway limited in their "speed".
