### ISSUE TITLE
Set batch size according to free GPU memory

### ISSUE THREAD

**Issue by konstin** [sacdallago/bio_embeddings#72]
The current `max_amino_acids` are for a GPU with 8GB. We should have at least a crude heuristic depending on the gpu memory.

**Comment by sacdallago** [comment]
This sounds good.

I actually don't know if LSF kills jobs that exceed the requested GPU RAM, but if that's so: one could run 2 tests and get a handwavey feeling:

- 8 GB requests, max size (we have)
- 10 GB requests, max size

we can then use the factor coming out from that to test a third case:

- 16GB request

----

this would obviosuly need to be run using each embedder once

**Comment by konstin** [comment]
The following are the model sizes by reserved memory on an RTX 8000: `{'prottrans_albert_bfd': 896069120, 'prottrans_bert_bfd': 1680044544, 'prottrans_xlnet_uniref100': 1637654528, 'seqvec': 374478336, 'esm': 2748142592, 'unirep': 0, 'cpcprot': 6841344, 'plus_rnn': 59661312, 'bepler': 67207168}`

**Comment by sacdallago** [comment]
Another instance of: feels like more work than gain at this point. Unless you already have the script @konstin ?

**Comment by konstin** [comment]
No, and unfortunately the max batch size (and even the max sequence length) change non-deterministically

**Comment by sacdallago** [comment]
yeah... let's then just shelve this for now
