### ISSUE TITLE
Autodocs for functions

### ISSUE THREAD

**Issue by sacdallago** [sacdallago/bio_embeddings#75]
From the discussions with Luisa on Slack, I believe we should have autodocs for the functions and modules in the pipeline.

I believe we did a good job documenting pipeline runs via the eamples folder, and have a quite good basis for the autodocs (e.g. many functions have return types and parameter types; many have function definitions). Can we set up readthedocs? Can we autogen this using gitlab/github CI?

**Comment by konstin** [comment]
This works, I'd track extending the current docs in new issues.
