### ISSUE TITLE
Docker build needs git

### ISSUE THREAD

**Issue by konstin** [sacdallago/bio_embeddings#79]
Currently missing, building the Dockerfile will fail

**Comment by sacdallago** [comment]
Could you document why? :) Just for the reference...

**Comment by konstin** [comment]
Sure: We're installing some python dependencies from their git repositories, since they aren't published on pypi and/or I had to patch them. poetry uses pip, and pip needs git in path to clone the repository (https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support, https://github.com/pypa/pip/blob/faee60baea2b850427b5fceb22383883fa11290b/src/pip/_internal/vcs/git.py#L254)

https://github.com/sacdallago/bio_embeddings/blob/8a5d878be0ffc24805b1cc2525e36d2367b8d7a0/pyproject.toml#L55-L58
