### ISSUE TITLE
Set number of threads

### ISSUE THREAD

**Issue by cjneely10** [sacdallago/bio_embeddings#8]
Good day,

Quick question: Is there any way to set the number of threads in the `bio_embeddings` pipeline - either from within the config file or from the command line?

Thank you.

**Comment by sacdallago** [comment]
Hey @cjneely10 
thanks for using the library.

- The CPU operations (e.g. data preparation etc.) performed by the pipeline are single threaded and we won't support multi-threading for these (in our experience this has never been necessary)

- The embedding operations are upscaled to all available CPU cores IF performed on CPU. Note that CPU usage is *not encouraged* (it sort of defeats the purpose). I can make a note of looking into how to allocate a specific number of CPU cores here, but ATM this would take lower priority.
