### ISSUE TITLE
Test pytorch 1.7

### ISSUE THREAD

**Issue by konstin** [sacdallago/bio_embeddings#80]
Check if any changes affect us

**Comment by sacdallago** [comment]
If 1.5 is not supported by Colab yet, I highligh doubt we are doing ourselves any favors by updating to 1.7 :D

**Comment by konstin** [comment]
We're currently installing ~1.5.0 so unless I'm missing something 1.5 is used in colab

**Comment by konstin** [comment]
I've also checked with a GPU runtime where I got `1.6.0+cu101` which worked, while installing 1.7.0 with pip triggers a message about cuda being to old. So I guess that one half of the answer if any changes in 1.7.0 affect us

**Comment by konstin** [comment]
Colab apparently upgrade to `1.7.0+cu101`, I think it would be good for us to try upgrading too. (We're currently uninstalling 1.7.0 and install 1.5.1 over it)
