### ISSUE TITLE
The notebook cannot be run in Google Colab 

### ISSUE THREAD

**Issue by deniseduma** [sacdallago/bio_embeddings#82]
Hi,

So yesterday I've tried uploading the notebook in my Google drive folder and then run it in Google Colab. I also tried the Google Colab link you added to my previous issue, however, the following errors occur when trying to use colab:

!pip3 install poetry > /dev/null
!pip3 install -U "bio-embeddings[all] @ git+https://github.com/sacdallago/bio_embeddings.git" > /dev/null

Running command git clone -q https://github.com/sacdallago/bio_embeddings.git /tmp/pip-install-0_ot8p8f/bio-embeddings
  Running command git clone -q https://github.com/facebookresearch/esm.git /tmp/pip-install-0_ot8p8f/esm
  Running command git checkout -q 84f05d0e57c917fdd4f47448723d0c1913aacf4a
  Running command git clone -q https://github.com/konstin/tape.git /tmp/pip-install-0_ot8p8f/tape-proteins
  Running command git checkout -b patch-1 --track origin/patch-1
  Switched to a new branch 'patch-1'
  Branch 'patch-1' set up to track remote branch 'patch-1' from 'origin'.
  Running command git clone -q https://github.com/amyxlu/CPCProt.git /tmp/pip-install-0_ot8p8f/cpcprot
  Running command git checkout -q df1ad1118544ed349b5e711207660a7c205b3128
  Running command git clone -q https://github.com/konstin/PLUS /tmp/pip-install-0_ot8p8f/plus
ERROR: torchvision 0.7.0+cu101 has requirement torch==1.6.0, but you'll have torch 1.5.1 which is incompatible.
ERROR: en-core-web-sm 2.2.5 has requirement spacy>=2.2.2, but you'll have spacy 2.1.9 which is incompatible.
ERROR: responses 0.12.0 has requirement urllib3>=1.25.10, but you'll have urllib3 1.24.3 which is incompatible.
ERROR: botocore 1.19.7 has requirement urllib3<1.26,>=1.25.4; python_version != "3.4", but you'll have urllib3 1.24.3 which is incompatible.

Apparently, there are incompatible versions between bioembeddings and colab, which is not necessarily a problem with bioembeddings but I'm not sure what to do about it, maybe you guys have a better idea of how to fix it??

Thanks,
Denise

**Comment by sacdallago** [comment]
Hi @deniseduma , again: thanks for reporting these issues. As far as my testing went, although these error messages appear, the package is installed nonetheless. Does this hold true for you as well? Specifically: is this issue blocking you from using the rest of the notebook?

I know "ERROR" doesn't read well, but I learned that on Colab it's useful to sometimes turn a blind eye...

I contacted a friend at G to ask him when they'd update Colab to more recent pip and CUDA versions (which should address these issues), and this should happen soon.

In the meantime, we have a private development branch in which @konstin is trying to address Colab "weirdness" (documented in #49 #78 #80 ). The current proposed solution is to change

```
!pip3 install poetry > /dev/null
!pip3 install -U "bio-embeddings[all] @ git+https://github.com/sacdallago/bio_embeddings.git" > /dev/null
```

to 

```
!pip3 install -U pip > /dev/null
!pip3 install -U "bio-embeddings[all] @ git+https://github.com/sacdallago/bio_embeddings.git" > /dev/null
```

but this seems to still rise some warnings and errors, and we have more internal testing to do before releasing this as a solution!

**Comment by deniseduma** [comment]
Hmm, you're right the notebook does work despite the error messages! 

I guess I just got intimidated by the word 'ERROR' in red! :P 

Thanks!

**Comment by sacdallago** [comment]
Yeah, I tried my best to "hide" the error :D aka the `> /dev/null`, but some things still pop up! I might want to add a note in the README to not be intimidated by the error messages (counterintuitive...).

This is very suboptimal, I wish such a highly used resource (Colab) would be more up to date :(

**Comment by deniseduma** [comment]
Hi again,

Sorry, me again! 

I've realized I need GPU on Google Colab to embed some 4000 human protein sequences but it seems I cannot get a GPU because of some incompatibility problem between the cuda driver in Google Colab and  the cuda version used by torch in bio-embeddings.

Here is the error I get:

import tensorflow as tf
print(tf.__version__)
print(tf.test.gpu_device_name())

2.3.0
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-20-bc9bec96459e> in <module>()
     12 import tensorflow as tf
     13 print(tf.__version__)
---> 14 print(tf.test.gpu_device_name())

1 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/device_lib.py in list_local_devices(session_config)
     41     serialized_config = session_config.SerializeToString()
     42   return [
---> 43       _convert(s) for s in _pywrap_device_lib.list_devices(serialized_config)
     44   ]

RuntimeError: cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version

Would it be possible to downgrade torch/cuda used by bio-embeddings so it is compatible with Colab for the time being?   

Alternatively, do you happen to have pre-computed embeddings for UniRef50 human proteins? 

Thanks,
Denise

**Comment by sacdallago** [comment]
Hi @deniseduma ,

> Would it be possible to downgrade torch/cuda used by bio-embeddings so it is compatible with Colab for the time being?

we are trying to look into how to solve this incompatibility in #49 and #80 . This issue was fixed a while ago but then suddely reappeared. For now, I don't have a colab solution.

> Alternatively, do you happen to have pre-computed embeddings for UniRef50 human proteins?

Unfortunately we don't have this set embedded.

> I've realized I need GPU on Google Colab to embed some 4000 human protein sequences but it seems I cannot get a GPU because of some incompatibility problem between the cuda driver in Google Colab and the cuda version used by torch in bio-embeddings.

4000 proteins we could embed for you if you send me a FASTA and config file! Just ping me on https://chat.bioembeddings.com to figure this out ;)

**Comment by deniseduma** [comment]
!python -V
import tensorflow as tf
print(tf.__version__)
#print(tf.test.gpu_device_name())





Ok, I've tried with PyTorch as well, same problem 

import torch 
print(torch.__version__)
print(torch.backends.cudnn.enabled)
print(torch.cuda.is_available())

Python 3.6.9
2.3.0
1.5.1
True
False
