### ISSUE TITLE
Mean potentially using incorrect axis

### ISSUE THREAD

**Issue by maffettone** [sacdallago/bio_embeddings#85]
https://github.com/sacdallago/bio_embeddings/blob/4ad42897173fe45f6ca9d2d7cdb1ed3a18e2b0d6/bio_embeddings/embed/unirep_embedder.py#L50

Unlike the paper _Nat Methods_ **16**, 1315–1322 (2019), and other embeddings in the package, this mean produces a per-residue average from the mLSTM as opposed to an average of hidden units across each amino acids (a per-protein representation). It is not clear if this is the intended behavior. 

Quick fix of `axis=0` if not intended.

**Comment by sacdallago** [comment]
Thank you for the excellent catch @maffettone !
