### ISSUE TITLE
Allow alignment of sequences through DeepBlast

### ISSUE THREAD

**Issue by sacdallago** [sacdallago/bio_embeddings#89]
https://github.com/flatironinstitute/deepblast

As discussed in the email with @mortonjt, once #87 is in, let's try to decide on an interface to integrate DeepBlast into bio_embeddings, and then test it out.

@konstin since you have worked most extensively with alignments using embeddings, I leave the choice of what to call this stage (or if to integrate this into the `extract` stage) up to you ;) We can draft implementation etc. together.

**Comment by konstin** [comment]
Done
