### ISSUE TITLE
Expand the documentation

### ISSUE THREAD

**Issue by konstin** [sacdallago/bio_embeddings#93]
Currently, the sphinx documentation contains only the api docs. We could extend this to contain all documentation we have:

 - [x] Readme
 - [x] yaml config examples
 - [x] notebooks (with links to open colab)
 - [x] api docs

@sacdallago What do you think?

**Comment by sacdallago** [comment]
I think by pulling in the README, we'll also cover a bit of the notebooks.

We could even pull in the README in /examples and /notebooks, I tried to keep those relevant. This would save us a lot of initial effort?

**Comment by sacdallago** [comment]
Note to self @sacdallago 
Add description, inputs and oputputs for https://docs.bioembeddings.com/modules/bio_embeddings.visualize.html

Relevant for protocol!

**Comment by konstin** [comment]
I don't think there's a good way to include the yaml examples in sphinx. I've created a new issue for the comment
